# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToDoApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from calendar import day_abbr
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
import datetime
today = date.today()
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InsertButton = QtWidgets.QPushButton(self.centralwidget)
        self.InsertButton.setGeometry(QtCore.QRect(200, 50, 161, 23))
        self.InsertButton.setObjectName("InsertButton")
        self.ListTasks = QtWidgets.QListWidget(self.centralwidget)
        self.ListTasks.setGeometry(QtCore.QRect(400, 10, 391, 471))
        self.ListTasks.setObjectName("ListTasks")
        self.InsertTask = QtWidgets.QLineEdit(self.centralwidget)
        self.InsertTask.setGeometry(QtCore.QRect(10, 10, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.InsertTask.setFont(font)
        self.InsertTask.setObjectName("InsertTask")
        self.TaskDate = QtWidgets.QDateEdit(self.centralwidget)
        self.TaskDate.setGeometry(QtCore.QRect(10, 50, 151, 22))
        self.TaskDate.setObjectName("TaskDate")
        self.TaskDate.setDate(today)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(450, 490, 291, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToDoCheckBox = QtWidgets.QCheckBox(self.widget)
        self.ToDoCheckBox.setObjectName("ToDoCheckBox")
        self.horizontalLayout.addWidget(self.ToDoCheckBox)
        self.InProgressCheckBox = QtWidgets.QCheckBox(self.widget)
        self.InProgressCheckBox.setObjectName("InProgressCheckBox")
        self.horizontalLayout.addWidget(self.InProgressCheckBox)
        self.DoneCheckBox = QtWidgets.QCheckBox(self.widget)
        self.DoneCheckBox.setObjectName("DoneCheckBox")
        self.horizontalLayout.addWidget(self.DoneCheckBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        print(today)
        class Task:
            def __init__(self, task, day, month, year):
                self.task = task
                self.day = day
                self.month = month
                self.year = year
            def made_date(self):
                self.date = datetime.datetime(self.year,self.month,self.day)
                self.date = self.date.strftime("%Y-%m-%d")
                return self.date
            def days_left(self):
                delta = self.date - today
        testowe = Task("Kupić",20,11,2022)
        print(testowe.made_date())
        print(testowe.days_left())



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InsertButton.setText(_translate("MainWindow", "Insert"))
        self.InsertTask.setPlaceholderText(_translate("MainWindow", "Insert task..."))
        self.ToDoCheckBox.setText(_translate("MainWindow", "To do"))
        self.InProgressCheckBox.setText(_translate("MainWindow", "In progress"))
        self.DoneCheckBox.setText(_translate("MainWindow", "Done"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    app.setStyle('Fusion')
    MainWindow.show()
    sys.exit(app.exec_())